// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: userfromrefreshtoken.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const userFromRefreshToken = `-- name: UserFromRefreshToken :one
SELECT
    user_id
from refresh_tokens
WHERE token = $1
`

func (q *Queries) UserFromRefreshToken(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, userFromRefreshToken, token)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
